package docgen

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"time"

	"module-dependency-visualizer/internal/graph"
	"module-dependency-visualizer/internal/provider"
	"module-dependency-visualizer/internal/schema"
)

// Options configures documentation output.
type Options struct {
	// Audit embeds vulnerability, conflict, and license data when non-nil.
	Audit *schema.AuditDTO
	// GeneratedAt overrides the timestamp in the document header.
	GeneratedAt time.Time
}

// Generate writes a Markdown document describing the dependency graph to w.
func Generate(w io.Writer, g *graph.Graph, proj provider.Project, opts Options) error {
	if opts.GeneratedAt.IsZero() {
		opts.GeneratedAt = time.Now().UTC()
	}

	nodes := g.Nodes()
	stats := g.Stats()

	var direct, indirect []graph.Node
	for _, n := range nodes {
		if n.Kind == graph.NodeKindMain {
			continue
		}
		if n.Indirect {
			indirect = append(indirect, n)
		} else {
			direct = append(direct, n)
		}
	}

	sortNodesByName(direct)
	sortNodesByName(indirect)

	// Build vuln / license indexes from audit data.
	vulnCount := make(map[string]int)
	licenseMap := make(map[string]string)
	if opts.Audit != nil {
		for _, v := range opts.Audit.Vulnerabilities {
			vulnCount[v.NodeID]++
		}
		licenseMap = opts.Audit.Licenses
	}

	// Header
	title := proj.Name
	if title == "" {
		title = "Dependencies"
	}
	fmt.Fprintf(w, "# Dependencies — %s\n\n", title)
	fmt.Fprintf(w, "> Generated by [mdv](https://github.com/devekkx/module-dependency-visualizer) on %s.\n\n",
		opts.GeneratedAt.Format("2006-01-02"))

	// Overview table
	fmt.Fprintf(w, "## Overview\n\n")
	fmt.Fprintf(w, "| Property | Value |\n")
	fmt.Fprintf(w, "|----------:|-------|\n")
	if proj.Language != "" {
		fmt.Fprintf(w, "| Language | %s |\n", proj.Language)
	}
	if proj.MainModule != "" {
		fmt.Fprintf(w, "| Main module | `%s` |\n", proj.MainModule)
	}
	fmt.Fprintf(w, "| Direct dependencies | %d |\n", len(direct))
	fmt.Fprintf(w, "| Indirect dependencies | %d |\n", len(indirect))
	fmt.Fprintf(w, "| Max depth | %d |\n", stats.MaxDepth)
	fmt.Fprintf(w, "| Cycles | %s |\n\n", boolLabel(stats.HasCycles, "Yes ⚠️", "No"))

	// Direct dependencies
	fmt.Fprintf(w, "## Direct Dependencies\n\n")
	if len(direct) == 0 {
		fmt.Fprintf(w, "_No direct dependencies._\n\n")
	} else {
		hasAudit := opts.Audit != nil
		if hasAudit {
			fmt.Fprintf(w, "| Module | Version | License | Vulnerabilities |\n")
			fmt.Fprintf(w, "|--------|---------|---------|:---------------:|\n")
			for _, n := range direct {
				lic := licenseMap[string(n.ID)]
				if lic == "" {
					lic = "—"
				}
				vc := vulnCount[string(n.ID)]
				vulnCell := "✅"
				if vc > 0 {
					vulnCell = fmt.Sprintf("⚠️ %d", vc)
				}
				fmt.Fprintf(w, "| `%s` | `%s` | %s | %s |\n", n.Name, n.Version, lic, vulnCell)
			}
		} else {
			fmt.Fprintf(w, "| Module | Version |\n")
			fmt.Fprintf(w, "|--------|:-------:|\n")
			for _, n := range direct {
				fmt.Fprintf(w, "| `%s` | `%s` |\n", n.Name, n.Version)
			}
		}
		fmt.Fprintf(w, "\n")
	}

	// Indirect dependencies (collapsible)
	fmt.Fprintf(w, "## Indirect Dependencies\n\n")
	if len(indirect) == 0 {
		fmt.Fprintf(w, "_No indirect dependencies._\n\n")
	} else {
		fmt.Fprintf(w, "<details>\n<summary>%d indirect %s</summary>\n\n",
			len(indirect), pluralize(len(indirect), "dependency", "dependencies"))
		fmt.Fprintf(w, "| Module | Version |\n")
		fmt.Fprintf(w, "|--------|:-------:|\n")
		for _, n := range indirect {
			fmt.Fprintf(w, "| `%s` | `%s` |\n", n.Name, n.Version)
		}
		fmt.Fprintf(w, "\n</details>\n\n")
	}

	// Security section (only when audit data is present)
	if opts.Audit != nil {
		fmt.Fprintf(w, "## Security\n\n")

		totalVulns := len(opts.Audit.Vulnerabilities)
		if totalVulns == 0 {
			fmt.Fprintf(w, "✅ No known vulnerabilities found (checked via [OSV](https://osv.dev)).\n\n")
		} else {
			fmt.Fprintf(w, "⚠️ **%d %s found** (via [OSV](https://osv.dev)).\n\n",
				totalVulns, pluralize(totalVulns, "vulnerability", "vulnerabilities"))
			fmt.Fprintf(w, "| Module | ID | Severity | Summary |\n")
			fmt.Fprintf(w, "|--------|----|----------|:--------|\n")
			for _, v := range opts.Audit.Vulnerabilities {
				summary := truncate(v.Summary, 80)
				link := v.Link
				if link == "" {
					link = "#"
				}
				fmt.Fprintf(w, "| `%s` | [%s](%s) | %s | %s |\n",
					v.NodeID, v.ID, link, v.Severity, summary)
			}
			fmt.Fprintf(w, "\n")
		}

		if len(opts.Audit.Conflicts) > 0 {
			fmt.Fprintf(w, "### Version Conflicts\n\n")
			fmt.Fprintf(w, "| Module | Versions |\n")
			fmt.Fprintf(w, "|--------|----------|\n")
			for _, c := range opts.Audit.Conflicts {
				fmt.Fprintf(w, "| `%s` | %s |\n", c.Module, strings.Join(c.Versions, " · "))
			}
			fmt.Fprintf(w, "\n")
		}
	}

	// Footer
	fmt.Fprintf(w, "---\n*Generated by [mdv](https://github.com/devekkx/module-dependency-visualizer) · schema v%s*\n",
		schema.Version)

	return nil
}

func sortNodesByName(ns []graph.Node) {
	sort.Slice(ns, func(i, j int) bool { return ns[i].Name < ns[j].Name })
}

func boolLabel(v bool, yes, no string) string {
	if v {
		return yes
	}
	return no
}

func pluralize(n int, singular, plural string) string {
	if n == 1 {
		return singular
	}
	return plural
}

func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max-3] + "…"
}
